package msitplacement;
// Generated Jun 8, 2017 11:22:38 AM by Hibernate Tools 4.3.1



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer id;
     private String rollnumber;
     private String sub;
     private String question;
     private String answer;

    public Comments() {
    }

    public Comments(String rollnumber, String sub, String question, String answer) {
       this.rollnumber = rollnumber;
       this.sub = sub;
       this.question = question;
       this.answer = answer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public String getSub() {
        return this.sub;
    }
    
    public void setSub(String sub) {
        this.sub = sub;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


