package msitplacement;
// Generated Jun 8, 2017 11:22:38 AM by Hibernate Tools 4.3.1



/**
 * Pc generated by hbm2java
 */
public class Pc  implements java.io.Serializable {


     private String rollnumber;
     private String name;
     private String password;
     private String email;
     private String phonenumber;

    public Pc() {
    }

	
    public Pc(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public Pc(String rollnumber, String name, String password, String email, String phonenumber) {
       this.rollnumber = rollnumber;
       this.name = name;
       this.password = password;
       this.email = email;
       this.phonenumber = phonenumber;
    }
   
    public String getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }




}


