package msitplacement;
// Generated Jun 8, 2017 11:22:38 AM by Hibernate Tools 4.3.1



/**
 * Postcompany generated by hbm2java
 */
public class Postcompany  implements java.io.Serializable {


     private String companyname;
     private String jobdesc;
     private String about;

    public Postcompany() {
    }

	
    public Postcompany(String companyname) {
        this.companyname = companyname;
    }
    public Postcompany(String companyname, String jobdesc, String about) {
       this.companyname = companyname;
       this.jobdesc = jobdesc;
       this.about = about;
    }
   
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    public String getJobdesc() {
        return this.jobdesc;
    }
    
    public void setJobdesc(String jobdesc) {
        this.jobdesc = jobdesc;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }




}


