package msitplacement;
// Generated Jun 8, 2017 11:22:38 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Postjobs generated by hbm2java
 */
public class Postjobs  implements java.io.Serializable {


     private String companyname;
     private Date date;
     private String venue;

    public Postjobs() {
    }

	
    public Postjobs(String companyname) {
        this.companyname = companyname;
    }
    public Postjobs(String companyname, Date date, String venue) {
       this.companyname = companyname;
       this.date = date;
       this.venue = venue;
    }
   
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getVenue() {
        return this.venue;
    }
    
    public void setVenue(String venue) {
        this.venue = venue;
    }




}


