package msitplacement;
// Generated Jun 8, 2017 11:22:38 AM by Hibernate Tools 4.3.1



/**
 * Resources generated by hbm2java
 */
public class Resources  implements java.io.Serializable {


     private Integer id;
     private String docName;
     private byte[] bytes;

    public Resources() {
    }

    public Resources(String docName, byte[] bytes) {
       this.docName = docName;
       this.bytes = bytes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDocName() {
        return this.docName;
    }
    
    public void setDocName(String docName) {
        this.docName = docName;
    }
    public byte[] getBytes() {
        return this.bytes;
    }
    
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }




}


