package msitplacement;
// Generated Jun 8, 2017 11:22:38 AM by Hibernate Tools 4.3.1



/**
 * Selectedlist generated by hbm2java
 */
public class Selectedlist  implements java.io.Serializable {


     private String companyname;
     private String rollnumber;
     private String studentName;

    public Selectedlist() {
    }

	
    public Selectedlist(String companyname) {
        this.companyname = companyname;
    }
    public Selectedlist(String companyname, String rollnumber, String studentName) {
       this.companyname = companyname;
       this.rollnumber = rollnumber;
       this.studentName = studentName;
    }
   
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    public String getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }




}


