package msitplacement;
// Generated Jun 8, 2017 11:22:38 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String rollnumber;
     private String name;
     private String password;
     private String gender;
     private String email;
     private Float masterpercent;
     private Float btechpercent;
     private Float interpercent;
     private Float sscpercent;
     private Float yeargap;
     private String status;
     private String phonenumber;

    public Student() {
    }

	
    public Student(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public Student(String rollnumber, String name, String password, String gender, String email, Float masterpercent, Float btechpercent, Float interpercent, Float sscpercent, Float yeargap, String status, String phonenumber) {
       this.rollnumber = rollnumber;
       this.name = name;
       this.password = password;
       this.gender = gender;
       this.email = email;
       this.masterpercent = masterpercent;
       this.btechpercent = btechpercent;
       this.interpercent = interpercent;
       this.sscpercent = sscpercent;
       this.yeargap = yeargap;
       this.status = status;
       this.phonenumber = phonenumber;
    }
   
    public String getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Float getMasterpercent() {
        return this.masterpercent;
    }
    
    public void setMasterpercent(Float masterpercent) {
        this.masterpercent = masterpercent;
    }
    public Float getBtechpercent() {
        return this.btechpercent;
    }
    
    public void setBtechpercent(Float btechpercent) {
        this.btechpercent = btechpercent;
    }
    public Float getInterpercent() {
        return this.interpercent;
    }
    
    public void setInterpercent(Float interpercent) {
        this.interpercent = interpercent;
    }
    public Float getSscpercent() {
        return this.sscpercent;
    }
    
    public void setSscpercent(Float sscpercent) {
        this.sscpercent = sscpercent;
    }
    public Float getYeargap() {
        return this.yeargap;
    }
    
    public void setYeargap(Float yeargap) {
        this.yeargap = yeargap;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }




}


